# Generated by Django 5.2.5 on 2025-09-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('factory_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('model_year', models.IntegerField(blank=True, max_length=4, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
