# Generated by Django 5.2.5 on 2025-10-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carinvetory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarInvetory',
            new_name='CarInventory',
        ),
    ]
